services:
  - type: web
    name: dreap-portal
    runtime: node
    rootDir: dreap
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
