import { Alert, Shelter, Contact, DisasterGuide, StatItem, FeatureCard, ProblemCard } from './types';

// ─── Emergency Contacts ────────────────────────────────────────────────────────
export const EMERGENCY_CONTACTS: Contact[] = [
  {
    id: '1',
    emoji: '🚨',
    name: 'National Emergency',
    number: '112',
    description: 'Single national emergency helpline — police, fire, ambulance',
    category: 'national',
  },
  {
    id: '2',
    emoji: '🚒',
    name: 'Fire & Rescue',
    number: '101',
    description: 'Fire brigade and rescue operations across all states',
    category: 'national',
  },
  {
    id: '3',
    emoji: '🏥',
    name: 'Ambulance',
    number: '108',
    description: 'Emergency medical services — free, 24×7 across India',
    category: 'national',
  },
  {
    id: '4',
    emoji: '👮',
    name: 'Police',
    number: '100',
    description: 'Law enforcement emergency response across all states',
    category: 'national',
  },
  {
    id: '5',
    emoji: '🌊',
    name: 'NDRF Helpline',
    number: '011-24363260',
    description: 'National Disaster Response Force — flood, quake, cyclone',
    category: 'national',
  },
  {
    id: '6',
    emoji: '🏛️',
    name: 'NDMA Control Room',
    number: '1078',
    description: 'National Disaster Management Authority — 24×7 operations',
    category: 'national',
  },
  {
    id: '7',
    emoji: '👩‍⚕️',
    name: 'Women Helpline',
    number: '1091',
    description: 'Emergency support for women in distress — nationwide',
    category: 'specialized',
  },
  {
    id: '8',
    emoji: '🧒',
    name: 'Child Helpline',
    number: '1098',
    description: 'CHILDLINE — 24 hour emergency service for children',
    category: 'specialized',
  },
  {
    id: '9',
    emoji: '🌡️',
    name: 'Poison Control',
    number: '1800-11-6117',
    description: 'National Poison Information Centre — free helpline',
    category: 'specialized',
  },
  {
    id: '10',
    emoji: '⚡',
    name: 'Gas Leak / GAIL',
    number: '1906',
    description: 'Gas emergency — leaks, explosions, pipeline incidents',
    category: 'specialized',
  },
  {
    id: '11',
    emoji: '🚁',
    name: 'Coast Guard',
    number: '1554',
    description: 'Marine emergencies — rescue, distress, coastal disasters',
    category: 'national',
  },
  {
    id: '12',
    emoji: '🔌',
    name: 'Power Emergency',
    number: '1912',
    description: 'Electricity emergencies — downed lines, electrocution risk',
    category: 'specialized',
  },
];

// ─── Mock Alert Data ───────────────────────────────────────────────────────────
export const MOCK_ALERTS: Alert[] = [
  {
    id: 'ALT001',
    severity: 'critical',
    title: 'Flash Flood Warning — Brahmaputra Basin',
    description: 'Severe flooding expected in low-lying areas of Assam. Water levels at Brahmaputra have exceeded danger mark by 2.3m. Immediate evacuation ordered.',
    zone: 'Assam — Dibrugarh, Jorhat, Sibsagar',
    disasterType: 'Flood',
    timestamp: '2 min ago',
    isNew: true,
  },
  {
    id: 'ALT002',
    severity: 'high',
    title: 'Cyclone Remal — Landfall Alert',
    description: 'Cyclone Remal approaching West Bengal coast. Wind speeds 130–150 km/h. Evacuation of coastal villages underway.',
    zone: 'West Bengal — South 24 Parganas, Sundarbans',
    disasterType: 'Cyclone',
    timestamp: '18 min ago',
    isNew: true,
  },
  {
    id: 'ALT003',
    severity: 'critical',
    title: 'Earthquake — 6.2 Magnitude Tremor',
    description: 'Significant earthquake recorded near Manipur-Myanmar border. Structural damage reported. Search and rescue teams deployed.',
    zone: 'Manipur — Churachandpur, Bishnupur',
    disasterType: 'Earthquake',
    timestamp: '34 min ago',
  },
  {
    id: 'ALT004',
    severity: 'high',
    title: 'Forest Fire — Uttarakhand',
    description: 'Active forest fire spreading across Nainital and Almora districts. Air quality index dangerously high. 3 villages on evacuation advisory.',
    zone: 'Uttarakhand — Nainital, Almora',
    disasterType: 'Fire',
    timestamp: '1 hr ago',
  },
  {
    id: 'ALT005',
    severity: 'medium',
    title: 'Heatwave Alert — Rajasthan',
    description: 'Maximum temperatures forecast above 46°C in multiple districts. Outdoor work restrictions in effect 11am–4pm. Hydration centers open.',
    zone: 'Rajasthan — Jaisalmer, Barmer, Bikaner',
    disasterType: 'Heatwave',
    timestamp: '2 hr ago',
  },
  {
    id: 'ALT006',
    severity: 'medium',
    title: 'Landslide Risk — NH44 Blocked',
    description: 'Heavy rainfall triggered landslides blocking National Highway 44. Alternate routes advised. NDRF teams clearing debris.',
    zone: 'Himachal Pradesh — Kullu, Manali',
    disasterType: 'Landslide',
    timestamp: '3 hr ago',
  },
  {
    id: 'ALT007',
    severity: 'info',
    title: 'Heavy Rainfall Advisory — Mumbai',
    description: 'IMD issues orange alert for Mumbai Metropolitan Region. Trains may be delayed. Low-lying areas to monitor water levels.',
    zone: 'Maharashtra — Mumbai, Thane, Raigad',
    disasterType: 'Flood',
    timestamp: '4 hr ago',
  },
  {
    id: 'ALT008',
    severity: 'resolved',
    title: 'Gas Leak — BPCL Refinery Contained',
    description: 'Minor gas leak at BPCL refinery in Kochi has been contained. No casualties. Area declared safe for re-entry.',
    zone: 'Kerala — Kochi, Ernakulam',
    disasterType: 'Industrial',
    timestamp: '6 hr ago',
  },
];

// ─── Mock Shelter Data ─────────────────────────────────────────────────────────
export const MOCK_SHELTERS: Shelter[] = [
  {
    id: 'SHE001',
    name: 'Rajendra Prasad Government School',
    type: 'school',
    address: 'Sector 12, Gandhinagar, Gujarat',
    district: 'Gandhinagar',
    state: 'Gujarat',
    distance: '0.8 km',
    capacity: 450,
    occupied: 210,
    facilities: ['food', 'water', 'medical', 'wheelchair'],
    lat: 23.2156,
    lng: 72.6369,
    phone: '079-23256789',
  },
  {
    id: 'SHE002',
    name: 'Ambedkar Community Hall',
    type: 'hall',
    address: 'Ward 7, Bhopal, Madhya Pradesh',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    distance: '1.2 km',
    capacity: 300,
    occupied: 278,
    facilities: ['food', 'water', 'medical'],
    lat: 23.2599,
    lng: 77.4126,
    phone: '0755-2551234',
  },
  {
    id: 'SHE003',
    name: 'Jawaharlal Nehru Indoor Stadium',
    type: 'stadium',
    address: 'Cuttack Road, Bhubaneswar, Odisha',
    district: 'Khordha',
    state: 'Odisha',
    distance: '2.1 km',
    capacity: 2000,
    occupied: 450,
    facilities: ['food', 'water', 'medical', 'wheelchair', 'pet'],
    lat: 20.2961,
    lng: 85.8245,
    phone: '0674-2546789',
  },
  {
    id: 'SHE004',
    name: 'Sri Ram Mandir Relief Camp',
    type: 'temple',
    address: 'Old Town, Patna, Bihar',
    district: 'Patna',
    state: 'Bihar',
    distance: '3.4 km',
    capacity: 150,
    occupied: 148,
    facilities: ['food', 'water'],
    lat: 25.5941,
    lng: 85.1376,
    phone: '0612-2678901',
  },
  {
    id: 'SHE005',
    name: 'Panchayat Bhavan Relief Center',
    type: 'community',
    address: 'Block HQ, Jorhat, Assam',
    district: 'Jorhat',
    state: 'Assam',
    distance: '4.7 km',
    capacity: 200,
    occupied: 95,
    facilities: ['water', 'medical'],
    lat: 26.7465,
    lng: 94.2026,
    phone: '0376-2323456',
  },
];

// ─── Safety Guidelines ────────────────────────────────────────────────────────
export const DISASTER_GUIDES: DisasterGuide[] = [
  {
    type: 'Flood',
    icon: '🌊',
    dangerLevel: 'Extreme',
    before: [
      { number: 1, title: 'Monitor Water Levels', description: 'Check NDMA alerts every 2 hours. Save offline shelter locations.', icon: '📡' },
      { number: 2, title: 'Prepare Emergency Kit', description: 'Water, food (3 days), medicines, torch, battery radio, important documents.', icon: '🎒' },
      { number: 3, title: 'Secure Your Home', description: 'Move valuables to upper floors. Turn off electricity at mains.', icon: '🏠' },
      { number: 4, title: 'Identify Evacuation Routes', description: 'Know 2 routes to your nearest shelter. Share plan with family.', icon: '🗺️' },
    ],
    during: [
      { number: 1, title: 'Evacuate Immediately', description: 'Do not wait for orders if water enters your home. Move to high ground.', icon: '🚶' },
      { number: 2, title: 'Avoid Floodwater', description: 'Never walk through moving water — 6 inches can knock you down.', icon: '⚠️' },
      { number: 3, title: 'Stay Off Roads', description: 'Most flood fatalities occur in vehicles. Abandon car if water rises.', icon: '🚗' },
      { number: 4, title: 'Signal for Help', description: 'If trapped, move to roof. Signal with bright cloth. Call 112.', icon: '🆘' },
    ],
    after: [
      { number: 1, title: 'Await Official Clearance', description: 'Return only after authorities declare area safe. Photograph damage.', icon: '✅' },
      { number: 2, title: 'Avoid Contaminated Water', description: 'Boil all water. Discard food that contacted floodwater.', icon: '💧' },
      { number: 3, title: 'Check Structural Safety', description: 'Do not enter damaged buildings. Call municipal engineer for inspection.', icon: '🏗️' },
      { number: 4, title: 'Document & Report', description: 'File damage report with local authority. Contact insurance provider.', icon: '📋' },
    ],
    dos: [
      'Store drinking water in sealed containers',
      'Keep emergency documents in waterproof bag',
      'Follow NDMA SMS alerts',
      'Help elderly neighbors evacuate',
      'Keep phone charged and power bank ready',
    ],
    donts: [
      'Do not drive through flooded roads',
      'Do not touch electrical equipment in wet areas',
      'Do not drink floodwater or use for cooking',
      'Do not return until authorities say it\'s safe',
      'Do not ignore evacuation orders',
    ],
    checklist: [
      'Emergency contacts saved offline',
      '3-day food and water supply',
      'Torches with fresh batteries',
      'First aid kit stocked',
      'Documents in waterproof bag',
      'Nearest shelter location saved',
      'Evacuation route agreed with family',
      'Power bank charged',
    ],
  },
  {
    type: 'Earthquake',
    icon: '🌍',
    dangerLevel: 'Extreme',
    before: [
      { number: 1, title: 'Secure Heavy Furniture', description: 'Anchor bookshelves, water heaters to walls. Store heavy items low.', icon: '🪑' },
      { number: 2, title: 'Know Safe Spots', description: 'Identify safe spots in each room — under sturdy tables, against interior walls.', icon: '🎯' },
      { number: 3, title: 'Prepare Emergency Kit', description: 'Include whistle, dust mask, gloves, water, food and first aid.', icon: '🎒' },
      { number: 4, title: 'Practice Drop-Cover-Hold', description: 'Rehearse earthquake drill with family every 6 months.', icon: '🔄' },
    ],
    during: [
      { number: 1, title: 'Drop-Cover-Hold On', description: 'Drop to hands and knees. Take cover under sturdy table. Hold on.', icon: '⬇️' },
      { number: 2, title: 'Stay Indoors', description: 'Stay away from windows, outside walls. Most injuries occur trying to run.', icon: '🏠' },
      { number: 3, title: 'If Outdoors, Move Clear', description: 'Move away from buildings, trees, streetlights. Drop to ground.', icon: '🌳' },
      { number: 4, title: 'If in Vehicle, Pull Over', description: 'Stop away from bridges and trees. Stay in vehicle until shaking stops.', icon: '🚗' },
    ],
    after: [
      { number: 1, title: 'Expect Aftershocks', description: 'Move outdoors after main quake. Aftershocks can collapse weakened structures.', icon: '📳' },
      { number: 2, title: 'Check for Injuries', description: 'Administer first aid. Do not move seriously injured unless in immediate danger.', icon: '🏥' },
      { number: 3, title: 'Inspect Utilities', description: 'Check for gas leaks, damaged electrical wiring. If in doubt, shut off.', icon: '⚡' },
      { number: 4, title: 'Stay Off Phones', description: 'Use phone only for emergencies. Keep lines open for rescue operations.', icon: '📵' },
    ],
    dos: [
      'Know your home\'s safe spots',
      'Keep shoes near your bed',
      'Store emergency kit in accessible location',
      'Learn to shut off gas and electricity',
      'Register on community alert system',
    ],
    donts: [
      'Do not run outside during shaking',
      'Do not stand in doorways (not safer)',
      'Do not use elevators after an earthquake',
      'Do not light matches or candles (gas risk)',
      'Do not enter damaged buildings',
    ],
    checklist: [
      'Heavy furniture anchored',
      'Safe spots identified in each room',
      'Emergency kit prepared',
      'Gas shutoff location known',
      'Family meeting point agreed',
      'First aid training completed',
      'Emergency contacts memorized',
      'Whistle and flashlight accessible',
    ],
  },
  {
    type: 'Fire',
    icon: '🔥',
    dangerLevel: 'High',
    before: [
      { number: 1, title: 'Install Smoke Alarms', description: 'One on each floor, inside every bedroom. Test monthly, replace batteries annually.', icon: '🚨' },
      { number: 2, title: 'Plan Two Exit Routes', description: 'Know two ways out of every room. Practice until it\'s automatic.', icon: '🚪' },
      { number: 3, title: 'Keep Fire Extinguisher', description: 'ABC-rated extinguisher in kitchen. Train family on PASS technique.', icon: '🧯' },
      { number: 4, title: 'Establish Meeting Point', description: 'Pick a meeting spot outside (mailbox, neighbor\'s house). Everyone must know it.', icon: '📍' },
    ],
    during: [
      { number: 1, title: 'GET OUT Immediately', description: 'Do not stop to collect belongings. Seconds matter in a house fire.', icon: '🚶' },
      { number: 2, title: 'Stay Low', description: 'Smoke rises. Crawl if needed. Clean air is near the floor.', icon: '⬇️' },
      { number: 3, title: 'Test Doors Before Opening', description: 'Feel door with back of hand. If hot, use alternate route.', icon: '🚪' },
      { number: 4, title: 'Call 101 Outside', description: 'Call fire services only after evacuating. Never re-enter.', icon: '📞' },
    ],
    after: [
      { number: 1, title: 'Stay Out', description: 'Do not re-enter until fire department declares building safe.', icon: '🚫' },
      { number: 2, title: 'Seek Medical Help', description: 'Smoke inhalation may not show symptoms immediately. Get evaluated.', icon: '🏥' },
      { number: 3, title: 'Contact Insurance', description: 'Document all damage with photographs before cleanup begins.', icon: '📸' },
      { number: 4, title: 'Notify Authorities', description: 'File report with local fire station. Claim relief if applicable.', icon: '📋' },
    ],
    dos: [
      'Test smoke alarms monthly',
      'Practice escape drill twice a year',
      'Keep portable extinguisher accessible',
      'Never leave cooking unattended',
      'Close bedroom doors while sleeping',
    ],
    donts: [
      'Do not stop for belongings',
      'Do not open hot doors',
      'Do not hide during a fire',
      'Do not re-enter burning building',
      'Do not use elevator in fire emergency',
    ],
    checklist: [
      'Smoke alarms installed on every floor',
      'Batteries replaced this year',
      'Two exit routes planned',
      'Fire extinguisher present',
      'Family meeting point set',
      'All family members practiced drill',
      'Emergency contacts saved',
      'Carbon monoxide detector installed',
    ],
  },
  {
    type: 'Heatwave',
    icon: '☀️',
    dangerLevel: 'High',
    before: [
      { number: 1, title: 'Prepare Cooling Supplies', description: 'Stock ORS packets, electrolytes. Identify nearby cooling centers.', icon: '🧊' },
      { number: 2, title: 'Check on Vulnerable People', description: 'Elderly, young children, outdoor workers need extra monitoring during heatwave.', icon: '👴' },
      { number: 3, title: 'Prepare Home', description: 'Install reflective window coverings. Check that fans/AC are working.', icon: '🏠' },
      { number: 4, title: 'Plan Outdoor Activities', description: 'Reschedule strenuous work to early morning or evening.', icon: '🕐' },
    ],
    during: [
      { number: 1, title: 'Stay Hydrated', description: 'Drink water every 20 minutes even if not thirsty. Avoid alcohol and caffeine.', icon: '💧' },
      { number: 2, title: 'Stay Indoors 11am–4pm', description: 'Avoid going outside during peak heat hours unless essential.', icon: '🌡️' },
      { number: 3, title: 'Recognize Heat Stroke', description: 'Hot dry skin, confusion, unconsciousness — call 108 immediately.', icon: '🏥' },
      { number: 4, title: 'Wear Light Clothing', description: 'Loose, light-colored, breathable cotton. Cover head outdoors.', icon: '👕' },
    ],
    after: [
      { number: 1, title: 'Rehydrate Gradually', description: 'Continue drinking fluids. Avoid cold showers immediately after extreme heat.', icon: '💧' },
      { number: 2, title: 'Rest and Recover', description: 'Allow body temperature to normalize naturally. Rest in cool area.', icon: '😴' },
      { number: 3, title: 'Monitor Health', description: 'Heat illness can have delayed effects. Seek medical care if feeling unwell.', icon: '🩺' },
      { number: 4, title: 'Report Heat Deaths', description: 'Report suspected heat-related deaths to district health officer.', icon: '📋' },
    ],
    dos: [
      'Drink at least 2.5 litres of water daily',
      'Wear light-colored loose clothing',
      'Use ORS if sweating excessively',
      'Check on neighbors and elderly daily',
      'Keep indoor plants for natural cooling',
    ],
    donts: [
      'Do not go out between 11am and 4pm',
      'Do not leave children in parked cars',
      'Do not consume alcohol during heatwave',
      'Do not do strenuous exercise in heat',
      'Do not skip meals — eat light and often',
    ],
    checklist: [
      'ORS packets stocked',
      'Cooling center location known',
      'Fans/AC checked and working',
      'Window coverings installed',
      'Vulnerable family members checked',
      'Light clothing available',
      'Water supply adequate',
      'Emergency numbers saved',
    ],
  },
  {
    type: 'Cyclone',
    icon: '🌀',
    dangerLevel: 'Extreme',
    before: [
      { number: 1, title: 'Track the Cyclone', description: 'Monitor IMD alerts. Know the cyclone\'s path and expected landfall time.', icon: '📡' },
      { number: 2, title: 'Secure Your Home', description: 'Board windows, secure loose objects outside. Park vehicles in garage.', icon: '🏠' },
      { number: 3, title: 'Prepare for 72 Hours', description: 'Store water, food, medicines, cash. Power may be out for days.', icon: '🎒' },
      { number: 4, title: 'Evacuate if Ordered', description: 'Obey mandatory evacuation orders. Cyclone shelters are built to withstand storms.', icon: '🚶' },
    ],
    during: [
      { number: 1, title: 'Stay in Shelter', description: 'Do not go outside during the storm. The eye offers false calm — storm resumes.', icon: '🏠' },
      { number: 2, title: 'Stay Away from Windows', description: 'Interior rooms are safest. Bathrooms and closets can provide protection.', icon: '🪟' },
      { number: 3, title: 'Avoid Floodwaters', description: 'Cyclones bring storm surge. Avoid all water on roads.', icon: '🌊' },
      { number: 4, title: 'Monitor Radio', description: 'Keep battery-powered radio on. Follow official instructions only.', icon: '📻' },
    ],
    after: [
      { number: 1, title: 'Wait for All-Clear', description: 'Do not leave shelter until official all-clear. Eye of storm creates false calm.', icon: '✅' },
      { number: 2, title: 'Avoid Damaged Structures', description: 'Report structural damage. Do not enter until inspected.', icon: '🏗️' },
      { number: 3, title: 'Boil All Water', description: 'Water systems may be contaminated. Use only boiled or bottled water.', icon: '💧' },
      { number: 4, title: 'Photograph Damage', description: 'Document all damage for insurance and government relief claims.', icon: '📸' },
    ],
    dos: [
      'Follow IMD cyclone tracker daily',
      'Stock 72-hour emergency supplies',
      'Secure or bring in outdoor furniture',
      'Charge all devices before cyclone hits',
      'Register with nearest cyclone shelter',
    ],
    donts: [
      'Do not venture out during cyclone',
      'Do not ignore mandatory evacuation orders',
      'Do not shelter under trees',
      'Do not touch fallen power lines',
      'Do not return home before official clearance',
    ],
    checklist: [
      '72-hour food and water supply',
      'Battery-powered radio available',
      'Mobile devices charged',
      'Windows boarded or shuttered',
      'Outdoor items secured',
      'Evacuation route identified',
      'Nearest cyclone shelter located',
      'Important documents waterproofed',
    ],
  },
  {
    type: 'Landslide',
    icon: '⛰️',
    dangerLevel: 'High',
    before: [
      { number: 1, title: 'Know Your Risk Zone', description: 'Check if your area is in landslide-prone zone. Contact district office.', icon: '🗺️' },
      { number: 2, title: 'Monitor Rainfall', description: 'Heavy prolonged rain precedes most landslides. Be alert after 48h+ of rain.', icon: '🌧️' },
      { number: 3, title: 'Watch Warning Signs', description: 'New cracks in soil, tilting trees, sudden spring appearance — evacuate immediately.', icon: '👁️' },
      { number: 4, title: 'Plan Escape Route', description: 'Move perpendicular to flow, not downhill. Know high ground locations.', icon: '🗺️' },
    ],
    during: [
      { number: 1, title: 'Move Quickly', description: 'Landslides move at 50+ km/h. Every second counts. Run perpendicular.', icon: '🏃' },
      { number: 2, title: 'Avoid River Valleys', description: 'Debris flows follow valley channels. Move to high stable ground.', icon: '⛰️' },
      { number: 3, title: 'If Buried, Stay Calm', description: 'Create breathing space around your face. Signal by knocking on solid objects.', icon: '🆘' },
      { number: 4, title: 'Stay Away from Slide Area', description: 'After initial slide, additional slides can follow. Do not re-enter area.', icon: '⚠️' },
    ],
    after: [
      { number: 1, title: 'Report Landslide', description: 'Contact NDRF at 1078. Provide exact location for rescue coordination.', icon: '📞' },
      { number: 2, title: 'Avoid Affected Area', description: 'Stay away until geologists declare area stable. Further slides likely.', icon: '🚫' },
      { number: 3, title: 'Check for Gas Leaks', description: 'Landslides can damage underground pipes. Check for smell before entering.', icon: '⚡' },
      { number: 4, title: 'Seek Structural Assessment', description: 'Have all buildings in affected zone inspected by civil engineer.', icon: '🏗️' },
    ],
    dos: [
      'Know your district risk level',
      'Monitor IMD rainfall warnings',
      'Plant trees to prevent soil erosion',
      'Know perpendicular escape routes',
      'Register for district alerts',
    ],
    donts: [
      'Do not ignore cracking sounds from hillside',
      'Do not camp near river valleys during monsoon',
      'Do not attempt rescue without equipment',
      'Do not return to zone until declared safe',
      'Do not build on steep slopes without approval',
    ],
    checklist: [
      'Risk zone status checked',
      'Perpendicular escape route planned',
      'Warning signs knowledge refreshed',
      'Emergency kit ready',
      'Local emergency contacts saved',
      'Family informed of escape plan',
      'Important documents secured',
      'Nearest high ground identified',
    ],
  },
];

// ─── Landing Page Stats ────────────────────────────────────────────────────────
export const HERO_STATS: StatItem[] = [
  { value: '18', label: 'Min avg alert time (current systems)', suffix: 'min' },
  { value: '99.9', label: 'Uptime target', suffix: '%' },
  { value: '12,000', label: 'Mapped shelters', suffix: '+' },
  { value: '12', label: 'Languages supported', suffix: '' },
];

export const PROBLEM_STATS: StatItem[] = [
  { value: '18', label: 'Minutes', suffix: 'min' },
  { value: '73', label: 'Of citizens don\'t know nearest shelter', suffix: '%' },
  { value: '4', label: 'Minutes before hotlines saturate', suffix: 'min' },
];

export const CTA_STATS: StatItem[] = [
  { value: '28', label: 'State governments evaluating', suffix: '+' },
  { value: '4.2M', label: 'Citizens in pilot regions', suffix: '' },
  { value: '67', label: 'Faster alert dissemination', suffix: '%' },
];

// ─── Feature Cards ─────────────────────────────────────────────────────────────
export const FEATURE_CARDS: FeatureCard[] = [
  {
    number: '01',
    icon: '📡',
    title: 'Real-Time Alert Feed',
    description: 'Multi-severity emergency broadcasts reach affected zones in under 90 seconds. SSE-powered, no page reload required.',
  },
  {
    number: '02',
    icon: '🗺️',
    title: 'Shelter Finder',
    description: '12,000+ mapped shelters with live capacity tracking. GPS-based routing opens your device\'s maps app in one tap.',
  },
  {
    number: '03',
    icon: '📖',
    title: 'Safety Protocols',
    description: 'Disaster-specific step-by-step guides for 6 disaster types. Downloadable for offline access in 12 regional languages.',
  },
  {
    number: '04',
    icon: '📞',
    title: 'Emergency Contacts',
    description: 'One-tap calling to all national emergency services. Optional GPS sharing with responders on connection.',
  },
  {
    number: '05',
    icon: '📝',
    title: 'Incident Reporting',
    description: 'Citizen-submitted incident reports with photo, GPS, and severity. Routes to nearest response unit automatically.',
  },
  {
    number: '06',
    icon: '📶',
    title: 'Offline Mode',
    description: 'Core features cached via service worker. Emergency contacts, shelters, and guidelines work without internet.',
  },
];

// ─── Problem Cards ─────────────────────────────────────────────────────────────
export const PROBLEM_CARDS: ProblemCard[] = [
  {
    icon: '⏱️',
    title: '18-Minute Alert Lag',
    description: 'Existing systems average 18 minutes to broadcast an alert. DREAP targets 90 seconds.',
  },
  {
    icon: '🏚️',
    title: '73% Don\'t Know Shelters',
    description: 'Nearly 3 in 4 citizens surveyed cannot name their nearest emergency shelter.',
  },
  {
    icon: '📵',
    title: 'Lines Saturate in 4 Minutes',
    description: 'Emergency hotlines overload within 4 minutes of any major event, leaving millions unreachable.',
  },
  {
    icon: '🧩',
    title: 'No Single Platform',
    description: 'Alerts, shelters, contacts, and reporting exist on separate systems — if they exist at all.',
  },
];

// ─── Architecture Data ─────────────────────────────────────────────────────────
export const ARCH_SOURCES = [
  { label: 'NDMA', desc: 'National alerts' },
  { label: 'IMD', desc: 'Weather data' },
  { label: 'ISRO', desc: 'Satellite imagery' },
  { label: 'State EOC', desc: 'Local incidents' },
];

export const ARCH_PLATFORM = [
  { label: 'API Gateway', desc: 'Fastify + Redis' },
  { label: 'Alert Engine', desc: 'SSE broadcast' },
  { label: 'Shelter DB', desc: 'PostGIS indexed' },
  { label: 'Report Queue', desc: 'BullMQ routing' },
];

export const ARCH_USERS = [
  { label: 'Citizens', desc: 'Public web + PWA' },
  { label: 'Responders', desc: 'Dashboard view' },
  { label: 'Agencies', desc: 'API integration' },
  { label: 'Media', desc: 'Public feed' },
];

export const TECH_STACK = {
  frontend: 'Next.js 14 · TypeScript · TailwindCSS · Framer Motion · Leaflet.js',
  backend: 'Node.js · Fastify · PostgreSQL/PostGIS · Redis · BullMQ · Socket.io',
  infrastructure: 'AWS Mumbai · CloudFront CDN · RDS Multi-AZ · S3 · Twilio / MSG91',
};

// ─── Incident Types ────────────────────────────────────────────────────────────
export const INCIDENT_TYPES = [
  { value: 'flood', label: '🌊 Flood', description: 'Flooding, waterlogging, rising water levels' },
  { value: 'fire', label: '🔥 Fire', description: 'Building fire, forest fire, gas fire' },
  { value: 'earthquake', label: '🌍 Earthquake', description: 'Tremor, structural collapse' },
  { value: 'accident', label: '🚗 Road Accident', description: 'Vehicle collision, road obstruction' },
  { value: 'medical', label: '🏥 Medical Emergency', description: 'Heart attack, unconscious, serious injury' },
  { value: 'missing', label: '👤 Missing Person', description: 'Person missing during or after disaster' },
  { value: 'structural', label: '🏗️ Building Collapse', description: 'Partial or full structural collapse' },
  { value: 'chemical', label: '☣️ Chemical Hazard', description: 'Gas leak, chemical spill, toxic exposure' },
  { value: 'other', label: '📋 Other', description: 'Any emergency not listed above' },
];
